sudo: required
dist: trusty
language: node_js
node_js:
  - "12.6.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  npm: true
  directories:
    - client/node_modules
    - server/node_modules

services:
  - mongodb

install:
  - cd server && npm install
  - cd ../client && npm install
  - npm install codecov

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # Server
  - cd ../server
  - npm run tslint
  - npm run test
  - npm run cover

  # Client
  - cd ../client
  - npm run lint
  - npm run test
  - npm run e2e
  - ng build --prod -- aot

after_script:
  - codecov
