
sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
  - "7"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - cd ../client
  - npm install -g angular-cli
  - npm install -g karma
  - npm install
  - ng build

script:

  # Client
  - cd ../client
  - npm run lint
  - npm run test
  - npm run e2e
  - ng build --prod -- aot
